"""stock_history, and notification tables added

Revision ID: 0d53d4de9e0f
Revises: d8efee6e22de
Create Date: 2026-08-19 11:32:14.688396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d53d4de9e0f'
down_revision: Union[str, Sequence[str], None] = 'd8efee6e22de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owner_notification_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('sub_info', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_owner_notification_subscriptions_user_id'), 'owner_notification_subscriptions', ['user_id'], unique=False)
    op.create_table('staff_notification_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.String(length=10), nullable=False),
    sa.Column('sub_info', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['staff_id'], ['staffs.staff_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_notification_subscriptions_staff_id'), 'staff_notification_subscriptions', ['staff_id'], unique=False)
    op.create_table('stock_histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sid', sa.UUID(), nullable=False),
    sa.Column('stock_slug', sa.String(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('staff_id', sa.String(length=10), nullable=True),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.String(length=20), nullable=False),
    sa.Column('action_type', sa.String(length=20), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['staff_id'], ['staffs.staff_id'], ),
    sa.ForeignKeyConstraint(['stock_slug'], ['stocks.slug'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.store_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_histories_sid'), 'stock_histories', ['sid'], unique=True)
    op.create_index(op.f('ix_stock_histories_stock_slug'), 'stock_histories', ['stock_slug'], unique=False)
    op.create_index(op.f('ix_stock_histories_store_id'), 'stock_histories', ['store_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_histories_store_id'), table_name='stock_histories')
    op.drop_index(op.f('ix_stock_histories_stock_slug'), table_name='stock_histories')
    op.drop_index(op.f('ix_stock_histories_sid'), table_name='stock_histories')
    op.drop_table('stock_histories')
    op.drop_index(op.f('ix_staff_notification_subscriptions_staff_id'), table_name='staff_notification_subscriptions')
    op.drop_table('staff_notification_subscriptions')
    op.drop_index(op.f('ix_owner_notification_subscriptions_user_id'), table_name='owner_notification_subscriptions')
    op.drop_table('owner_notification_subscriptions')
    # ### end Alembic commands ###
