"""add pin_hash and pin_salt to users

Revision ID: 243a7a174eb7
Revises: 38d4df61016b
Create Date: 2026-08-31 15:48:20.834799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '243a7a174eb7'
down_revision: Union[str, Sequence[str], None] = '38d4df61016b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pin_hash', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('pin_salt', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pin_salt')
    op.drop_column('users', 'pin_hash')
    # ### end Alembic commands ###
