"""add resend_id to email_messages

Revision ID: 38d4df61016b
Revises: 71a507e7a41b
Create Date: 2026-08-31 13:31:36.445288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38d4df61016b'
down_revision: Union[str, Sequence[str], None] = '71a507e7a41b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_messages', sa.Column('resend_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_email_messages_resend_id'), 'email_messages', ['resend_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_messages_resend_id'), table_name='email_messages')
    op.drop_column('email_messages', 'resend_id')
    # ### end Alembic commands ###
