"""modified

Revision ID: 53db48f9ef7f
Revises: ced6a3c44a8f
Create Date: 2026-08-29 17:57:03.952112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53db48f9ef7f'
down_revision: Union[str, Sequence[str], None] = 'ced6a3c44a8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_mailboxes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mailbox_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('PERSONAL', 'SHARED', name='mailboxtype'), nullable=False),
    sa.Column('owner_admin_id', sa.UUID(), nullable=True),
    sa.Column('allowed_admin_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_admin_id'], ['admins.admin_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_mailboxes_email'), 'email_mailboxes', ['email'], unique=True)
    op.create_index(op.f('ix_email_mailboxes_mailbox_id'), 'email_mailboxes', ['mailbox_id'], unique=True)
    op.create_index(op.f('ix_email_mailboxes_owner_admin_id'), 'email_mailboxes', ['owner_admin_id'], unique=False)
    op.create_index(op.f('ix_email_mailboxes_type'), 'email_mailboxes', ['type'], unique=False)
    op.add_column('admins', sa.Column('company_email', sa.String(length=255), nullable=False))
    op.add_column('admins', sa.Column('personal_email', sa.String(length=255), nullable=False))
    op.drop_index(op.f('ix_admins_access_token'), table_name='admins')
    op.drop_index(op.f('ix_admins_email'), table_name='admins')
    op.create_index(op.f('ix_admins_company_email'), 'admins', ['company_email'], unique=True)
    op.create_index(op.f('ix_admins_personal_email'), 'admins', ['personal_email'], unique=True)
    op.drop_column('admins', 'email')
    op.drop_column('admins', 'access_token')
    op.add_column('email_threads', sa.Column('mailbox_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_email_threads_mailbox_id'), 'email_threads', ['mailbox_id'], unique=False)
    op.create_foreign_key(None, 'email_threads', 'email_mailboxes', ['mailbox_id'], ['mailbox_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'email_threads', type_='foreignkey')
    op.drop_index(op.f('ix_email_threads_mailbox_id'), table_name='email_threads')
    op.drop_column('email_threads', 'mailbox_id')
    op.add_column('admins', sa.Column('access_token', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('admins', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_admins_personal_email'), table_name='admins')
    op.drop_index(op.f('ix_admins_company_email'), table_name='admins')
    op.create_index(op.f('ix_admins_email'), 'admins', ['email'], unique=True)
    op.create_index(op.f('ix_admins_access_token'), 'admins', ['access_token'], unique=True)
    op.drop_column('admins', 'personal_email')
    op.drop_column('admins', 'company_email')
    op.drop_index(op.f('ix_email_mailboxes_type'), table_name='email_mailboxes')
    op.drop_index(op.f('ix_email_mailboxes_owner_admin_id'), table_name='email_mailboxes')
    op.drop_index(op.f('ix_email_mailboxes_mailbox_id'), table_name='email_mailboxes')
    op.drop_index(op.f('ix_email_mailboxes_email'), table_name='email_mailboxes')
    op.drop_table('email_mailboxes')
    # ### end Alembic commands ###
