"""catalog table add, cost price column added to stock

Revision ID: 6d3be17e0917
Revises: 23be59d77db3
Create Date: 2026-09-06 10:43:53.302628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d3be17e0917'
down_revision: Union[str, Sequence[str], None] = '23be59d77db3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalog_templates_is_active'), 'catalog_templates', ['is_active'], unique=False)
    op.create_index(op.f('ix_catalog_templates_slug'), 'catalog_templates', ['slug'], unique=True)
    op.create_table('catalog_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('barcode', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('suggested_price', sa.Integer(), nullable=False),
    sa.Column('cost_price', sa.Integer(), nullable=False),
    sa.Column('unit_in', sa.String(length=10), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['catalog_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalog_items_barcode'), 'catalog_items', ['barcode'], unique=False)
    op.create_index(op.f('ix_catalog_items_category'), 'catalog_items', ['category'], unique=False)
    op.create_index(op.f('ix_catalog_items_name'), 'catalog_items', ['name'], unique=False)
    op.create_index('ix_catalog_items_template_barcode', 'catalog_items', ['template_id', 'barcode'], unique=False)
    op.create_index(op.f('ix_catalog_items_template_id'), 'catalog_items', ['template_id'], unique=False)
    op.add_column('stocks', sa.Column('cost_price', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stocks', 'cost_price')
    op.drop_index(op.f('ix_catalog_items_template_id'), table_name='catalog_items')
    op.drop_index('ix_catalog_items_template_barcode', table_name='catalog_items')
    op.drop_index(op.f('ix_catalog_items_name'), table_name='catalog_items')
    op.drop_index(op.f('ix_catalog_items_category'), table_name='catalog_items')
    op.drop_index(op.f('ix_catalog_items_barcode'), table_name='catalog_items')
    op.drop_table('catalog_items')
    op.drop_index(op.f('ix_catalog_templates_slug'), table_name='catalog_templates')
    op.drop_index(op.f('ix_catalog_templates_is_active'), table_name='catalog_templates')
    op.drop_table('catalog_templates')
    # ### end Alembic commands ###
