"""pin added

Revision ID: 6d4af8e9a72f
Revises: 53db48f9ef7f
Create Date: 2026-08-30 16:36:39.489817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d4af8e9a72f'
down_revision: Union[str, Sequence[str], None] = '53db48f9ef7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_notification_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.UUID(), nullable=False),
    sa.Column('sub_info', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.admin_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_notification_subscriptions_admin_id'), 'admin_notification_subscriptions', ['admin_id'], unique=False)
    op.add_column('daily_platform_metrics', sa.Column('total_merchants', sa.Integer(), nullable=False))
    op.add_column('daily_platform_metrics', sa.Column('new_merchants_today', sa.Integer(), nullable=False))
    op.add_column('daily_platform_metrics', sa.Column('total_staff', sa.Integer(), nullable=False))
    op.add_column('daily_platform_metrics', sa.Column('total_products', sa.Integer(), nullable=False))
    op.add_column('daily_platform_metrics', sa.Column('total_transactions', sa.Integer(), nullable=False))
    op.add_column('daily_platform_metrics', sa.Column('total_gmv', sa.BigInteger(), nullable=False))
    op.add_column('daily_platform_metrics', sa.Column('total_tickets_open', sa.Integer(), nullable=False))
    op.add_column('daily_platform_metrics', sa.Column('total_emails_unread', sa.Integer(), nullable=False))
    op.drop_column('daily_platform_metrics', 'total_sales_count')
    op.drop_column('daily_platform_metrics', 'new_staff_created')
    op.drop_column('daily_platform_metrics', 'total_offline_synced_sales')
    op.drop_column('daily_platform_metrics', 'new_users_registered')
    op.drop_column('daily_platform_metrics', 'total_revenue_amount')
    op.add_column('staffs', sa.Column('pin_hash', sa.String(length=255), nullable=True))
    op.add_column('staffs', sa.Column('pin_salt', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staffs', 'pin_salt')
    op.drop_column('staffs', 'pin_hash')
    op.add_column('daily_platform_metrics', sa.Column('total_revenue_amount', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('daily_platform_metrics', sa.Column('new_users_registered', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('daily_platform_metrics', sa.Column('total_offline_synced_sales', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('daily_platform_metrics', sa.Column('new_staff_created', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('daily_platform_metrics', sa.Column('total_sales_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('daily_platform_metrics', 'total_emails_unread')
    op.drop_column('daily_platform_metrics', 'total_tickets_open')
    op.drop_column('daily_platform_metrics', 'total_gmv')
    op.drop_column('daily_platform_metrics', 'total_transactions')
    op.drop_column('daily_platform_metrics', 'total_products')
    op.drop_column('daily_platform_metrics', 'total_staff')
    op.drop_column('daily_platform_metrics', 'new_merchants_today')
    op.drop_column('daily_platform_metrics', 'total_merchants')
    op.drop_index(op.f('ix_admin_notification_subscriptions_admin_id'), table_name='admin_notification_subscriptions')
    op.drop_table('admin_notification_subscriptions')
    # ### end Alembic commands ###
