"""expand staff_notification_subscriptions staff_id length

Revision ID: 71a507e7a41b
Revises: 24b516d275dd
Create Date: 2026-08-30 19:19:58.637678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71a507e7a41b'
down_revision: Union[str, Sequence[str], None] = '24b516d275dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
