"""add_analytics_used_and_description_to_subscriptions

Revision ID: 8d3fb6296a31
Revises: dcc2faa64803
Create Date: 2026-09-02 22:48:59.041629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d3fb6296a31'
down_revision: Union[str, Sequence[str], None] = 'dcc2faa64803'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_subscriptions', sa.Column('analytics_used', sa.Integer(), server_default='0', nullable=False))
    op.add_column('user_subscriptions', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_subscriptions', 'description')
    op.drop_column('user_subscriptions', 'analytics_used')
    # ### end Alembic commands ###
