"""add_cost_price_to_sale_items_and_is_default_to_plans

Revision ID: b97daa974e1f
Revises: cb898acca48a
Create Date: 2026-09-12 17:19:01.428568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b97daa974e1f'
down_revision: Union[str, Sequence[str], None] = 'cb898acca48a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sale_items', sa.Column('cost_price', sa.Integer(), nullable=True))
    op.add_column('subscription_plans', sa.Column('is_default', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription_plans', 'is_default')
    op.drop_column('sale_items', 'cost_price')
    # ### end Alembic commands ###
