"""add total_imports to catalog_templates

Revision ID: cb898acca48a
Revises: 6d3be17e0917
Create Date: 2026-09-06 11:06:55.385638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb898acca48a'
down_revision: Union[str, Sequence[str], None] = '6d3be17e0917'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalog_templates', sa.Column('total_imports', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('catalog_templates', 'total_imports')
    # ### end Alembic commands ###
