"""email no longer compulsary for customer

Revision ID: ce5394b7da05
Revises: b97daa974e1f
Create Date: 2026-09-14 17:44:21.366064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce5394b7da05'
down_revision: Union[str, Sequence[str], None] = 'b97daa974e1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customers', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('customers_email_key'), 'customers', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('customers_email_key'), 'customers', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('customers', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
