"""admin models add update on existing model (notification)

Revision ID: ced6a3c44a8f
Revises: 0d53d4de9e0f
Create Date: 2026-08-29 15:24:01.921367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ced6a3c44a8f'
down_revision: Union[str, Sequence[str], None] = '0d53d4de9e0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.UUID(), nullable=False),
    sa.Column('fullname', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('access_token', sa.String(length=500), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('otp_token', sa.String(length=255), nullable=True),
    sa.Column('otp_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'ADMIN', 'MODERATOR', name='adminrole'), nullable=False),
    sa.Column('permission', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INVITED', 'SUSPENDED', 'REVOKED', name='adminstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admins_access_token'), 'admins', ['access_token'], unique=True)
    op.create_index(op.f('ix_admins_admin_id'), 'admins', ['admin_id'], unique=True)
    op.create_index(op.f('ix_admins_email'), 'admins', ['email'], unique=True)
    op.create_index(op.f('ix_admins_otp_token'), 'admins', ['otp_token'], unique=True)
    op.create_table('daily_platform_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_stores', sa.Integer(), nullable=False),
    sa.Column('active_stores', sa.Integer(), nullable=False),
    sa.Column('total_sales_count', sa.Integer(), nullable=False),
    sa.Column('total_revenue_amount', sa.BigInteger(), nullable=False),
    sa.Column('total_offline_synced_sales', sa.Integer(), nullable=False),
    sa.Column('new_users_registered', sa.Integer(), nullable=False),
    sa.Column('new_staff_created', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_platform_metrics_date'), 'daily_platform_metrics', ['date'], unique=True)
    op.create_table('email_campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('sender', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SCHEDULED', 'SENDING', 'SENT', 'FAILED', name='emailcampaignstatus'), nullable=False),
    sa.Column('target_audience', sa.String(length=100), nullable=False),
    sa.Column('total_recipients', sa.Integer(), nullable=False),
    sa.Column('total_delivered', sa.Integer(), nullable=False),
    sa.Column('total_failed', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_campaigns_campaign_id'), 'email_campaigns', ['campaign_id'], unique=True)
    op.create_index(op.f('ix_email_campaigns_status'), 'email_campaigns', ['status'], unique=False)
    op.create_table('email_threads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.UUID(), nullable=False),
    sa.Column('customer_email', sa.String(), nullable=False),
    sa.Column('to', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('snippet', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('UNREAD', 'READ', 'ARCHIVED', 'SPAM', 'DELETED', name='emailthreadstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_threads_customer_email'), 'email_threads', ['customer_email'], unique=False)
    op.create_index(op.f('ix_email_threads_last_message_at'), 'email_threads', ['last_message_at'], unique=False)
    op.create_index(op.f('ix_email_threads_status'), 'email_threads', ['status'], unique=False)
    op.create_index(op.f('ix_email_threads_thread_id'), 'email_threads', ['thread_id'], unique=True)
    op.create_index(op.f('ix_email_threads_to'), 'email_threads', ['to'], unique=False)
    op.create_table('notification_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_type', sa.Enum('STAFF', 'USER', 'ADMIN', name='notificationrecipienttype'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('sub_info', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_subscriptions_user_id'), 'notification_subscriptions', ['user_id'], unique=False)
    op.create_index(op.f('ix_notification_subscriptions_user_type'), 'notification_subscriptions', ['user_type'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notification_id', sa.UUID(), nullable=False),
    sa.Column('scope', sa.Enum('PERSONAL', 'STORE', 'GLOBAL', name='notificationscope'), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_notification_id'), 'notifications', ['notification_id'], unique=True)
    op.create_index(op.f('ix_notifications_scope'), 'notifications', ['scope'], unique=False)
    op.create_index(op.f('ix_notifications_target_id'), 'notifications', ['target_id'], unique=False)
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_settings_key'), 'system_settings', ['key'], unique=True)
    op.create_table('admin_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('log_id', sa.UUID(), nullable=False),
    sa.Column('admin_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.admin_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_audit_logs_action'), 'admin_audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_admin_audit_logs_admin_id'), 'admin_audit_logs', ['admin_id'], unique=False)
    op.create_index(op.f('ix_admin_audit_logs_created_at'), 'admin_audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_admin_audit_logs_log_id'), 'admin_audit_logs', ['log_id'], unique=True)
    op.create_index(op.f('ix_admin_audit_logs_target_id'), 'admin_audit_logs', ['target_id'], unique=False)
    op.create_index(op.f('ix_admin_audit_logs_target_type'), 'admin_audit_logs', ['target_type'], unique=False)
    op.create_table('admin_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('admin_id', sa.UUID(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=64), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('expired_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.admin_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_sessions_admin_id'), 'admin_sessions', ['admin_id'], unique=False)
    op.create_index(op.f('ix_admin_sessions_refresh_token_hash'), 'admin_sessions', ['refresh_token_hash'], unique=True)
    op.create_index(op.f('ix_admin_sessions_session_id'), 'admin_sessions', ['session_id'], unique=True)
    op.create_table('email_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('thread_id', sa.UUID(), nullable=False),
    sa.Column('mail_id', sa.String(), nullable=True),
    sa.Column('recipients', sa.String(), nullable=False),
    sa.Column('sender', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('in_reply_to', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['thread_id'], ['email_threads.thread_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_messages_created_at'), 'email_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_email_messages_direction'), 'email_messages', ['direction'], unique=False)
    op.create_index(op.f('ix_email_messages_mail_id'), 'email_messages', ['mail_id'], unique=False)
    op.create_index(op.f('ix_email_messages_message_id'), 'email_messages', ['message_id'], unique=True)
    op.create_index(op.f('ix_email_messages_thread_id'), 'email_messages', ['thread_id'], unique=False)
    op.create_table('notification_reads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('notification_id', sa.UUID(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.notification_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_reads_notification_id'), 'notification_reads', ['notification_id'], unique=False)
    op.create_index(op.f('ix_notification_reads_user_id'), 'notification_reads', ['user_id'], unique=False)
    op.create_table('support_tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=True),
    sa.Column('reporter_type', sa.String(length=20), nullable=False),
    sa.Column('reporter_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('BUG', 'HARDWARE', 'FEATURE', 'GENERAL', name='tickettype'), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('device_diagnostics', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', name='ticketstatus'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='ticketpriority'), nullable=False),
    sa.Column('assigned_admin_id', sa.UUID(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_admin_id'], ['admins.admin_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.store_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_support_tickets_assigned_admin_id'), 'support_tickets', ['assigned_admin_id'], unique=False)
    op.create_index(op.f('ix_support_tickets_created_at'), 'support_tickets', ['created_at'], unique=False)
    op.create_index(op.f('ix_support_tickets_priority'), 'support_tickets', ['priority'], unique=False)
    op.create_index(op.f('ix_support_tickets_reporter_id'), 'support_tickets', ['reporter_id'], unique=False)
    op.create_index(op.f('ix_support_tickets_reporter_type'), 'support_tickets', ['reporter_type'], unique=False)
    op.create_index(op.f('ix_support_tickets_status'), 'support_tickets', ['status'], unique=False)
    op.create_index(op.f('ix_support_tickets_store_id'), 'support_tickets', ['store_id'], unique=False)
    op.create_index(op.f('ix_support_tickets_ticket_id'), 'support_tickets', ['ticket_id'], unique=True)
    op.create_index(op.f('ix_support_tickets_type'), 'support_tickets', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_support_tickets_type'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_ticket_id'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_store_id'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_status'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_reporter_type'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_reporter_id'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_priority'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_created_at'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_assigned_admin_id'), table_name='support_tickets')
    op.drop_table('support_tickets')
    op.drop_index(op.f('ix_notification_reads_user_id'), table_name='notification_reads')
    op.drop_index(op.f('ix_notification_reads_notification_id'), table_name='notification_reads')
    op.drop_table('notification_reads')
    op.drop_index(op.f('ix_email_messages_thread_id'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_message_id'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_mail_id'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_direction'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_created_at'), table_name='email_messages')
    op.drop_table('email_messages')
    op.drop_index(op.f('ix_admin_sessions_session_id'), table_name='admin_sessions')
    op.drop_index(op.f('ix_admin_sessions_refresh_token_hash'), table_name='admin_sessions')
    op.drop_index(op.f('ix_admin_sessions_admin_id'), table_name='admin_sessions')
    op.drop_table('admin_sessions')
    op.drop_index(op.f('ix_admin_audit_logs_target_type'), table_name='admin_audit_logs')
    op.drop_index(op.f('ix_admin_audit_logs_target_id'), table_name='admin_audit_logs')
    op.drop_index(op.f('ix_admin_audit_logs_log_id'), table_name='admin_audit_logs')
    op.drop_index(op.f('ix_admin_audit_logs_created_at'), table_name='admin_audit_logs')
    op.drop_index(op.f('ix_admin_audit_logs_admin_id'), table_name='admin_audit_logs')
    op.drop_index(op.f('ix_admin_audit_logs_action'), table_name='admin_audit_logs')
    op.drop_table('admin_audit_logs')
    op.drop_index(op.f('ix_system_settings_key'), table_name='system_settings')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_notifications_target_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_scope'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_notification_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_notification_subscriptions_user_type'), table_name='notification_subscriptions')
    op.drop_index(op.f('ix_notification_subscriptions_user_id'), table_name='notification_subscriptions')
    op.drop_table('notification_subscriptions')
    op.drop_index(op.f('ix_email_threads_to'), table_name='email_threads')
    op.drop_index(op.f('ix_email_threads_thread_id'), table_name='email_threads')
    op.drop_index(op.f('ix_email_threads_status'), table_name='email_threads')
    op.drop_index(op.f('ix_email_threads_last_message_at'), table_name='email_threads')
    op.drop_index(op.f('ix_email_threads_customer_email'), table_name='email_threads')
    op.drop_table('email_threads')
    op.drop_index(op.f('ix_email_campaigns_status'), table_name='email_campaigns')
    op.drop_index(op.f('ix_email_campaigns_campaign_id'), table_name='email_campaigns')
    op.drop_table('email_campaigns')
    op.drop_index(op.f('ix_daily_platform_metrics_date'), table_name='daily_platform_metrics')
    op.drop_table('daily_platform_metrics')
    op.drop_index(op.f('ix_admins_otp_token'), table_name='admins')
    op.drop_index(op.f('ix_admins_email'), table_name='admins')
    op.drop_index(op.f('ix_admins_admin_id'), table_name='admins')
    op.drop_index(op.f('ix_admins_access_token'), table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###
