"""scope_barcode_unique_per_store

Revision ID: d624891c255d
Revises: 64fea0e0f99b
Create Date: 2026-09-04 09:37:59.166197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd624891c255d'
down_revision: Union[str, Sequence[str], None] = '64fea0e0f99b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('stocks_barcode_id_key'), 'stocks', type_='unique')
    op.create_index(op.f('ix_stocks_barcode_id'), 'stocks', ['barcode_id'], unique=False)
    op.create_index('uq_stocks_store_barcode', 'stocks', ['store_id', 'barcode_id'], unique=True, postgresql_where=sa.text("deleted = false AND barcode_id IS NOT NULL AND barcode_id != ''"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_stocks_store_barcode', table_name='stocks', postgresql_where=sa.text("deleted = false AND barcode_id IS NOT NULL AND barcode_id != ''"))
    op.drop_index(op.f('ix_stocks_barcode_id'), table_name='stocks')
    op.create_unique_constraint(op.f('stocks_barcode_id_key'), 'stocks', ['barcode_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
