"""add_subscription_tables_and_paystack_fields

Revision ID: dd51e831b9ed
Revises: cf9bd89b6b02
Create Date: 2026-09-02 21:10:47.929304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd51e831b9ed'
down_revision: Union[str, Sequence[str], None] = 'cf9bd89b6b02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('store_limit', sa.Integer(), nullable=True),
    sa.Column('product_limit', sa.Integer(), nullable=True),
    sa.Column('sales_limit_per_month', sa.Integer(), nullable=True),
    sa.Column('analytics_read_per_month', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'UNAVAILABLE', name='planstatus'), nullable=False),
    sa.Column('paystack_planid', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_plans_name'), 'subscription_plans', ['name'], unique=True)
    op.create_index(op.f('ix_subscription_plans_slug'), 'subscription_plans', ['slug'], unique=True)
    op.create_table('user_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'DUE', 'EXPIRED', name='subscriptionstatus'), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('paystack_subscription_code', sa.String(length=100), nullable=True),
    sa.Column('payment_channel', sa.Enum('PAYSTACK', 'MONIFY', name='paymentchannel'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('next_renewal', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.slug'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_subscriptions_idempotency_key'), 'user_subscriptions', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_user_subscriptions_paystack_subscription_code'), 'user_subscriptions', ['paystack_subscription_code'], unique=False)
    op.create_index(op.f('ix_user_subscriptions_plan_id'), 'user_subscriptions', ['plan_id'], unique=False)
    op.create_index(op.f('ix_user_subscriptions_reference'), 'user_subscriptions', ['reference'], unique=True)
    op.create_index(op.f('ix_user_subscriptions_subscription_id'), 'user_subscriptions', ['subscription_id'], unique=True)
    op.create_index(op.f('ix_user_subscriptions_user_id'), 'user_subscriptions', ['user_id'], unique=False)
    op.add_column('users', sa.Column('current_subscription_id', sa.UUID(), nullable=True))
    op.add_column('users', sa.Column('paystack_customer_code', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('paystack_authorization', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_users_current_subscription_id'), 'users', ['current_subscription_id'], unique=False)
    op.create_index(op.f('ix_users_paystack_customer_code'), 'users', ['paystack_customer_code'], unique=True)
    op.create_foreign_key(None, 'users', 'user_subscriptions', ['current_subscription_id'], ['subscription_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_paystack_customer_code'), table_name='users')
    op.drop_index(op.f('ix_users_current_subscription_id'), table_name='users')
    op.drop_column('users', 'paystack_authorization')
    op.drop_column('users', 'paystack_customer_code')
    op.drop_column('users', 'current_subscription_id')
    op.drop_index(op.f('ix_user_subscriptions_user_id'), table_name='user_subscriptions')
    op.drop_index(op.f('ix_user_subscriptions_subscription_id'), table_name='user_subscriptions')
    op.drop_index(op.f('ix_user_subscriptions_reference'), table_name='user_subscriptions')
    op.drop_index(op.f('ix_user_subscriptions_plan_id'), table_name='user_subscriptions')
    op.drop_index(op.f('ix_user_subscriptions_paystack_subscription_code'), table_name='user_subscriptions')
    op.drop_index(op.f('ix_user_subscriptions_idempotency_key'), table_name='user_subscriptions')
    op.drop_table('user_subscriptions')
    op.drop_index(op.f('ix_subscription_plans_slug'), table_name='subscription_plans')
    op.drop_index(op.f('ix_subscription_plans_name'), table_name='subscription_plans')
    op.drop_table('subscription_plans')
    # ### end Alembic commands ###
