"""store_id, added to debt, deleted added to customer

Revision ID: e3569603ab3d
Revises: ce5394b7da05
Create Date: 2026-09-15 12:09:07.747979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3569603ab3d'
down_revision: Union[str, Sequence[str], None] = 'ce5394b7da05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.add_column('customers', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('debt', sa.Column('store_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_debt_store_id'), 'debt', ['store_id'], unique=False)
    op.create_foreign_key(None, 'debt', 'stores', ['store_id'], ['store_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'debt', type_='foreignkey')
    op.drop_index(op.f('ix_debt_store_id'), table_name='debt')
    op.drop_column('debt', 'store_id')
    op.drop_column('customers', 'deleted_at')
    op.drop_column('customers', 'deleted')
    # ### end Alembic commands ###
