"""add previous_refresh_token_hash to user_sessions and staff_sessions

Revision ID: f4a0054ff26d
Revises: 243a7a174eb7
Create Date: 2026-09-02 10:22:24.201717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4a0054ff26d'
down_revision: Union[str, Sequence[str], None] = '243a7a174eb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff_sessions', sa.Column('previous_refresh_token_hash', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_staff_sessions_previous_refresh_token_hash'), 'staff_sessions', ['previous_refresh_token_hash'], unique=False)
    op.add_column('user_sessions', sa.Column('previous_refresh_token_hash', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_user_sessions_previous_refresh_token_hash'), 'user_sessions', ['previous_refresh_token_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_sessions_previous_refresh_token_hash'), table_name='user_sessions')
    op.drop_column('user_sessions', 'previous_refresh_token_hash')
    op.drop_index(op.f('ix_staff_sessions_previous_refresh_token_hash'), table_name='staff_sessions')
    op.drop_column('staff_sessions', 'previous_refresh_token_hash')
    # ### end Alembic commands ###
